#ifndef CONF_H
#define CONF_H

#define BASE_OFFSET_X 0
#define BASE_OFFSET_Y 0
#define BASE_ANGLE 2
#define BASE_SCOPE_SCALE 1

#define CENTER_CROSSHAIR_SIZE 15
#define CENTER_CROSSHAIR_THICKNESS 3
#define CENTER_CROSSHAIR_COLOR 8

#define LISTENING_PORT 50000

#define FIXED_AR qreal(0.75)

#define SCOPE_ANGLE_TO_THND qreal(20)

#endif // CONF_H
